'use client';

import { motion } from 'framer-motion';
import { AlertTriangle, ArrowRight, Bot, Building2, FileText, Mail, Scale, Users } from 'lucide-react';
import Link from 'next/link';

const sections = [
  {
    icon: Users,
    title: 'Using HireFlow',
    color: 'text-violet-400',
    iconBg: 'bg-violet-500/10 border-violet-500/20',
    dot: 'bg-violet-400',
    content: [
      { heading: 'Eligibility', text: 'You must be at least 16 years old to use HireFlow. By creating an account you confirm you meet this requirement and that all information you provide is accurate.' },
      { heading: 'Account Responsibility', text: 'You are responsible for maintaining the security of your account credentials and for all activity under your account. Notify us immediately at security@hireflow.com if you suspect unauthorized access.' },
      { heading: 'Prohibited Conduct', text: 'You may not post false job listings, spam other users, scrape the platform, attempt to reverse-engineer our AI systems, or use HireFlow for any unlawful purpose.' },
    ],
  },
  {
    icon: Building2,
    title: 'For Companies',
    color: 'text-blue-400',
    iconBg: 'bg-blue-500/10 border-blue-500/20',
    dot: 'bg-blue-400',
    content: [
      { heading: 'Job Listing Accuracy', text: 'All job listings must be for genuine, currently open positions. Ghost listings, misleading compensation ranges, or fictitious roles will result in immediate account suspension.' },
      { heading: 'Approval Process', text: 'Company accounts are reviewed before gaining access to posting features. We reserve the right to reject or revoke approval at our discretion if our policies are violated.' },
      { heading: 'Candidate Data', text: 'You may only use applicant data (cover letters, resume URLs) to evaluate candidates for the specific role they applied to. Sharing or selling this data to third parties is strictly prohibited.' },
    ],
  },
  {
    icon: Bot,
    title: 'AI Features',
    color: 'text-fuchsia-400',
    iconBg: 'bg-fuchsia-500/10 border-fuchsia-500/20',
    dot: 'bg-fuchsia-400',
    content: [
      { heading: 'AI-Generated Content', text: 'Cover letters, job descriptions, and recommendations generated by our AI are starting points — not guarantees. You are responsible for reviewing and customizing all AI-generated content before using it.' },
      { heading: 'No Reliance Warranty', text: 'Our AI Job Recommendations are based on pattern matching and do not constitute career advice. We make no guarantee that applying to recommended jobs will result in an offer.' },
      { heading: 'Usage Limits', text: 'AI features are subject to rate limits to ensure fair access for all users. Automated or excessive use of AI endpoints outside normal platform usage may result in temporary restrictions.' },
    ],
  },
  {
    icon: AlertTriangle,
    title: 'Limitations & Liability',
    color: 'text-orange-400',
    iconBg: 'bg-orange-500/10 border-orange-500/20',
    dot: 'bg-orange-400',
    content: [
      { heading: 'Service Availability', text: 'We aim for 99.9% uptime but do not guarantee uninterrupted service. We may perform maintenance with advance notice where possible and are not liable for downtime-related losses.' },
      { heading: 'Third-Party Content', text: 'HireFlow does not endorse or guarantee the accuracy of job listings, company descriptions, or any content posted by users. Exercise your own judgment when applying to positions.' },
      { heading: 'Liability Cap', text: 'To the maximum extent permitted by law, HireFlow\'s total liability for any claim arising from use of the platform is limited to the amount you paid us in the 12 months preceding the claim (or $100 if you\'ve paid nothing).' },
    ],
  },
];

const quickPoints = [
  { emoji: '✅', text: 'Free for job seekers, always' },
  { emoji: '📋', text: 'Companies must post real, open roles' },
  { emoji: '🤖', text: 'AI content is a tool, not a guarantee' },
  { emoji: '🚫', text: 'No spamming, scraping, or fake accounts' },
  { emoji: '🗑️', text: 'Delete your account any time' },
  { emoji: '⚖️', text: 'Governed by the laws of California, USA' },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">

      {/* Hero */}
      <section className="relative py-24 overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <motion.div className="absolute top-1/3 right-1/4 w-96 h-96 bg-blue-500/6 rounded-full blur-3xl"
            animate={{ x: [0, -25, 0] }} transition={{ duration: 14, repeat: Infinity }} />
          <motion.div className="absolute bottom-0 left-1/4 w-72 h-72 bg-violet-500/5 rounded-full blur-3xl"
            animate={{ x: [0, 20, 0] }} transition={{ duration: 11, repeat: Infinity, delay: 2 }} />
          <div className="absolute inset-0 opacity-[0.015]"
            style={{ backgroundImage: 'radial-gradient(circle at 1px 1px, rgba(124,58,237,0.8) 1px, transparent 0)', backgroundSize: '40px 40px' }} />
        </div>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative text-center">
          <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/20 mb-8">
              <Scale className="w-3.5 h-3.5 text-blue-400" />
              <span className="text-xs font-bold text-blue-400 uppercase tracking-widest">Legal Agreement</span>
            </div>
            <h1 className="text-5xl md:text-6xl font-bold text-foreground mb-5 leading-none">
              Terms of{' '}
              <span className="bg-gradient-to-r from-blue-400 to-indigo-400 bg-clip-text text-transparent">Service</span>
            </h1>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto leading-relaxed mb-6">
              Plain English. No legal jargon. Here's what you agree to when using HireFlow.
            </p>
            <p className="text-xs text-muted-foreground">Last updated: May 1, 2025 · Effective immediately for new users</p>
          </motion.div>
        </div>
      </section>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">

        {/* Quick summary */}
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
          className="bg-gradient-to-br from-blue-500/10 to-indigo-600/5 border border-blue-500/20 rounded-2xl p-6 mb-10">
          <div className="flex items-center gap-2 mb-4">
            <FileText className="w-4 h-4 text-blue-400" />
            <p className="text-sm font-bold text-blue-400">TL;DR — The 30-second version</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {quickPoints.map((p) => (
              <div key={p.text} className="flex items-center gap-2.5">
                <span className="text-base">{p.emoji}</span>
                <span className="text-sm text-foreground">{p.text}</span>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Acceptance note */}
        <motion.div initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
          className="bg-card border border-border rounded-2xl p-5 mb-6">
          <p className="text-sm text-muted-foreground leading-relaxed">
            <span className="font-semibold text-foreground">By creating an account or using HireFlow</span>, you agree to these Terms of Service and our{' '}
            <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>. If you do not agree, please do not use the platform.
          </p>
        </motion.div>

        {/* Sections */}
        <div className="space-y-6">
          {sections.map((section, i) => {
            const Icon = section.icon;
            return (
              <motion.div key={section.title}
                initial={{ opacity: 0, y: 25 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.07, duration: 0.5 }}
                className="bg-card border border-border rounded-2xl overflow-hidden">

                <div className="flex items-center gap-4 p-6 border-b border-border">
                  <div className={`w-10 h-10 rounded-xl ${section.iconBg} border flex items-center justify-center flex-shrink-0`}>
                    <Icon className={`w-5 h-5 ${section.color}`} />
                  </div>
                  <h2 className="text-lg font-bold text-foreground">{section.title}</h2>
                </div>

                <div className="divide-y divide-border">
                  {section.content.map((item, j) => (
                    <motion.div key={item.heading}
                      initial={{ opacity: 0, x: -10 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: i * 0.07 + j * 0.05 }}
                      className="flex gap-4 p-5">
                      <div className={`w-1.5 h-1.5 rounded-full ${section.dot} mt-2 flex-shrink-0`} />
                      <div>
                        <p className="text-sm font-semibold text-foreground mb-1">{item.heading}</p>
                        <p className="text-sm text-muted-foreground leading-relaxed">{item.text}</p>
                      </div>
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            );
          })}
        </div>

        {/* Termination */}
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
          className="mt-6 bg-card border border-border rounded-2xl p-6">
          <h2 className="text-base font-bold text-foreground mb-3 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-orange-400" /> Termination
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            You can delete your account at any time from your profile settings. We may suspend or terminate accounts that violate these terms, with or without notice depending on severity. Upon termination, your right to use HireFlow ceases immediately, and your data will be deleted per our Privacy Policy.
          </p>
        </motion.div>

        {/* Governing law */}
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
          className="mt-4 bg-card border border-border rounded-2xl p-6">
          <h2 className="text-base font-bold text-foreground mb-3 flex items-center gap-2">
            <Scale className="w-4 h-4 text-blue-400" /> Governing Law
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            These Terms are governed by the laws of the State of California, United States, without regard to conflict of law principles. Any disputes shall be resolved through binding arbitration in San Francisco, CA, except where prohibited by law.
          </p>
        </motion.div>

        {/* Contact */}
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
          className="mt-6 flex flex-col sm:flex-row items-center justify-between gap-4 p-6 bg-gradient-to-br from-blue-500/10 to-indigo-600/5 border border-blue-500/20 rounded-2xl">
          <div className="flex items-center gap-3">
            <Mail className="w-5 h-5 text-blue-400 flex-shrink-0" />
            <div>
              <p className="text-sm font-bold text-foreground">Questions about these terms?</p>
              <p className="text-xs text-muted-foreground">Our legal team responds within 48 hours</p>
            </div>
          </div>
          <a href="mailto:legal@hireflow.com"
            className="flex items-center gap-2 px-5 py-2.5 bg-blue-500/15 border border-blue-500/30 text-blue-400 font-semibold rounded-xl hover:bg-blue-500/20 transition-colors text-sm whitespace-nowrap">
            legal@hireflow.com <ArrowRight className="w-3.5 h-3.5" />
          </a>
        </motion.div>

        <motion.p initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}
          className="text-center text-sm text-muted-foreground mt-8">
          Also read our{' '}
          <Link href="/privacy" className="text-primary hover:underline font-semibold">Privacy Policy</Link>
        </motion.p>
      </div>
    </div>
  );
}